spring:
  application:
    name: shop
  datasource:
    url: jdbc:h2:mem:shopdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html